[{"count": 0, "tags": [], "bug_id": 18853, "attachment_id": null, "id": 34789, "time": "2003-04-09T12:25:22Z", "creator": "jkb@stian.freeserve.co.uk", "creation_time": "2003-04-09T12:25:22Z", "is_private": false, "text": "If there is a problem connecting to a database via JDBC (e.g. the wrong \ndatabase name) then JMeter keeps trying the same request over and over, and \ndoes not seem to give up at all ...\n\nSample trace (showing JMeter classes only):\n04/09/2003 12:48:53 PM ERROR - jmeter.protocol.jdbc:  java.sql.SQLException: \nFatal db error: could not open db \"dbnane\" for user \"USER\" : E_US0010 Database \ndoes not exist: 'dbname'.\n    (WED APR  9 12:48:50 2003)\n...\n\tat java.sql.DriverManager.getConnection(DriverManager.java:512)\n\tat java.sql.DriverManager.getConnection(DriverManager.java:171)\n\tat org.apache.jmeter.protocol.jdbc.util.DBConnectionManager.setup\n(DBConnectionManager.java:162)\n\tat org.apache.jmeter.protocol.jdbc.util.DBConnectionManager.getKey\n(DBConnectionManager.java:134)\n\tat org.apache.jmeter.protocol.jdbc.sampler.JDBCSampler.getKey\n(JDBCSampler.java:269)\n\tat org.apache.jmeter.protocol.jdbc.sampler.JDBCSampler.sample\n(JDBCSampler.java:151)\n\tat org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:158)\n\tat java.lang.Thread.run(Thread.java:536)\n\n04/09/2003 12:48:56 PM ERROR - jmeter.protocol.jdbc: ConnectionObject: url = \njdbc:.../dbname java.sql.SQLException: Fatal db error: could not open \ndb \"dbname\" for user \"USER\" : E_US0010 Database does not exist: 'dbname'.\n    (WED APR  9 12:48:52 2003)\n...\n\tat java.sql.DriverManager.getConnection(DriverManager.java:512)\n\tat java.sql.DriverManager.getConnection(DriverManager.java:171)\n\tat \norg.apache.jmeter.protocol.jdbc.util.DBConnectionManager.newConnection\n(DBConnectionManager.java:246)\n\tat org.apache.jmeter.protocol.jdbc.util.ConnectionObject.reset\n(ConnectionObject.java:254)\n\tat org.apache.jmeter.protocol.jdbc.util.ConnectionObject.run\n(ConnectionObject.java:226)\n\tat java.lang.Thread.run(Thread.java:536)\n\n====================================\n\nHope to look at this in more detail soon; maybe post a patch...."}, {"count": 1, "tags": [], "text": "Yes, it's very persistent.  JMeter is not a quitter!", "attachment_id": null, "id": 36114, "creator": "mstover1@apache.org", "time": "2003-04-25T15:45:59Z", "bug_id": 18853, "creation_time": "2003-04-25T15:45:59Z", "is_private": false}, {"count": 2, "tags": [], "bug_id": 18853, "attachment_id": null, "id": 36293, "time": "2003-04-29T13:59:37Z", "creator": "mstover1@apache.org", "creation_time": "2003-04-29T13:59:37Z", "is_private": false, "text": "Should be fixed.  JMeter will throw exceptions from the connection manager and\nthe sample will fail each time.  But,the connection manager won't keep trying\nforever."}]