[{"count": 0, "tags": [], "creator": "tekn0@libero.it", "attachment_id": null, "text": "I've a problem with mod_jk2 connector (2.0.2) with Apache 2.0.43 and Tomcat \n4.1.27.\n\nAfter a bit, log file (error_log) writes this lines:\n\n[Wed Oct 15 12:08:32 2003] [error] Error ajp_process_callback - write failed\n[Wed Oct 15 12:08:32 2003] [error] ajp13.service() ajpGetReply recoverable \nerror 3\n[Wed Oct 15 12:08:32 2003] [error] Error ajp_process_callback - write failed\n[Wed Oct 15 12:08:32 2003] [error] ajp13.service() ajpGetReply recoverable \nerror 3\n[Wed Oct 15 12:08:32 2003] [error] ajp13.service() Error  forwarding \najp13:localhost:8009 1 0\n[Wed Oct 15 12:08:32 2003] [error] mod_jk.handler() Error connecting to tomcat \n3\n\nThis's my configuration files:\n\n************* BEGIN jk2.properties ****************\nhandler.list=apr,channelSocket,request\n\nchannelSocket.port=8009\n\nserverRoot=/usr/local/apache\n\napr.NativeSo = /usr/local/apache/modules/jkjni.so\n************* ENDjk2.properties ****************\n\n************* BEGIN workers2.properties ****************\n# Shared memory handling.\n[shm:]\nfile=/usr/local/apache/conf/shm.file\nsize=1048576\n\n[config]\nfile=/usr/local/apache/conf/workers2.properties\ndebug=10\ndebugEnv=10\n\n[channel.socket:localhost:8009]\nport=8009\nhost=127.0.0.1\ntomcatId=localhost:8009\n\n[ajp13:localhost:8009]\nchannel=channel.socket:localhost:8009\n\n# Uri mapping.\n[uri:/*]\nworker=ajp13:localhost:8009\n************* END workers2.properties ****************\n\n************* BEGIN server.xml ****************\n<Server port=\"8005\" shutdown=\"SHUTDOWN\" debug=\"0\">\n\t<Service name=\"Tomcat-Apache\">\n\t\t<Connector className=\"org.apache.ajp.tomcat4.Ajp13Connector\" \nport=\"8009\" minProcessors=\"20\" maxProcessors=\"200\" acceptCount=\"10\" debug=\"0\" \naddress=\"127.0.0.1\"/>\n\t\t<Engine name=\"Server\" defaultHost=\"localhost\" debug=\"0\">\n\t\t\t<Logger \nclassName=\"org.apache.catalina.logger.FileLogger\" prefix=\"catalina_log.\" \nsuffix=\".log\" timestamp=\"true\"/>\n\t\t\t<Realm \nclassName=\"org.apache.catalina.realm.MemoryRealm\" />\n\t\t\t<Host name=\"localhost\" debug=\"0\" appBase=\"webapps\" \nunpackWARs=\"true\" autoDeploy=\"true\">\n\t\t\t\t<Logger \nclassName=\"org.apache.catalina.logger.FileLogger\" directory=\"logs\"  \nprefix=\"localhost_log.\" suffix=\".log\" timestamp=\"true\"/>\n\t\t\t\t<Context path=\"\" docBase=\"\" debug=\"0\"/>\n\t\t\t</Host>\n\t\t</Engine>\n\t</Service>\n</Server>\n************* END server.xml ****************\n\nThe strange think is that until a few day ago this server isn't problems.\n\nPlease help me\n\nPier", "id": 45724, "time": "2003-10-15T10:21:36Z", "bug_id": 23831, "creation_time": "2003-10-15T10:21:36Z", "is_private": false}, {"count": 1, "text": "Some strange problems with Apache and Tomcat...After some\ntime and server-stress, Apache doesn't response to requests which are\nrouted to tomcat...Another ... There're much more java (35 processes) and \napache (20 proc) processes running on my server ... and with netstat command I \nhave almost 20 internet connection to 8009 port\n\nIt's strange ... I think that tomcat not release connection after use...is it \npossible ??!\n\nThanks", "creator": "tekn0@libero.it", "attachment_id": null, "id": 45746, "time": "2003-10-15T16:08:27Z", "bug_id": 23831, "creation_time": "2003-10-15T16:08:27Z", "tags": [], "is_private": false}, {"count": 2, "tags": [], "creator": "tekn0@libero.it", "text": "Some strange problems with Apache and Tomcat...After some\ntime and server-stress, Apache doesn't response to requests which are\nrouted to tomcat...Another ... There're much more java (35 processes) and \napache (20 proc) processes running on my server ... and with netstat command I \nhave almost 20 internet connection to 8009 port\n\nIt's strange ... I think that tomcat not release connection after use...is it \npossible ??!\n\nThanks", "id": 45748, "time": "2003-10-15T16:13:41Z", "bug_id": 23831, "creation_time": "2003-10-15T16:13:41Z", "is_private": false, "attachment_id": null}, {"count": 3, "tags": [], "creator": "hgomez@apache.org", "text": "Thanks to revalidate with latest jk2 CVS and latest TC 4.1.30 (there was fix in\nThreadPools)", "id": 52321, "time": "2004-02-16T08:37:50Z", "bug_id": 23831, "creation_time": "2004-02-16T08:37:50Z", "is_private": false, "attachment_id": null}]