[{"count": 0, "tags": [], "bug_id": 2541, "text": "When handling a parser validation error, the method call \n\n  parser.getProperty(\"http://apache.org/xml/properties/dom/current-element-\nnode\"); \n\nnormally returns the document node where the validation error occurs.\nI say normally, because there is an exception to the rule which is probably a \nbug:\n\nSCHEMA (schema.xsd)\n===================\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<xsd:schema xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n\t<xsd:element name=\"Root\">\n\t\t<xsd:complexType>\n\t\t\t<xsd:sequence>\n\t\t\t\t<xsd:element name=\"Element\">\n                                        <xsd:complexType>\n                                            <xsd:attribute name=\"attr2\" \ntype=\"xsd:int\" fixed=\"2\"/>\n                                        </xsd:complexType>\n                                </xsd:element>\n\t\t\t</xsd:sequence>\n\t\t\t<xsd:attribute name=\"attr1\" type=\"xsd:int\" fixed=\"1\"/>\n\t\t</xsd:complexType>\n\t</xsd:element>\n</xsd:schema>\n\nDOCUMENT (doc.xml)\n==================\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Root xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" \nxsi:noNamespaceSchemaLocation=\"schema.xsd\" attr1=\"9\">\n\t<Element attr2=\"9\"/>\n</Root>\n\n\nDESCRIPTION OF TEST\n===================\nThe sax errorhandler is called twice during validation of this code.\n\na. The \"attr1\" attribute of the Root element has the illegal value \"9\" (it is \ndefined as \"fixed=1\" in the schema).\nb. The \"attr2\" attribute\" of the Element element has the illegal value \"9\" (it \nis defined as \"fixed=2\" in the schema).\n\nRetrieval of the \"http://apache.org/xml/properties/dom/current-element-node\" \nproperty during handling of the second error returns the current node (the \nElement element), as expected.\n\nHowever, this property retrieval FAILS during handling of the first error, \ninstead of returning the Root element as it should.", "id": 3550, "time": "2001-07-10T09:33:26Z", "creator": "maoz@xacct.com", "creation_time": "2001-07-10T09:33:26Z", "is_private": false, "attachment_id": null}, {"count": 1, "tags": [], "bug_id": 2541, "text": "I don't think this is bug.\nAt the point where you get the error, the element node is not created yet \n(because the attributes are not ready). So for the first error, the current \nnode is the document (current element is \"null\"), and for the second error, the \ncurrent node is \"root\" (not \"Element\").", "id": 3643, "time": "2001-07-11T09:07:55Z", "creator": "sandygao@ca.ibm.com", "creation_time": "2001-07-11T09:07:55Z", "is_private": false, "attachment_id": null}]