[{"count": 0, "tags": [], "bug_id": 36433, "attachment_id": null, "id": 79211, "time": "2005-08-31T05:07:36Z", "creator": "lew.payne@gmail.com", "creation_time": "2005-08-31T05:07:36Z", "is_private": false, "text": "The apache ErrorLog does not log 408 (request timeout) errors.  Instead, they \nappear in the normal TransferLog.  Can someone please fix this behaviour or \ngive me a hint as to where in the code these decisions are made?  I have an \napp that relies on \"[error]\" conditions appearing in the error log.  Thanks."}]