[{"count": 0, "tags": [], "bug_id": 52041, "text": "2011-10-13/10:03:21.115/EDT [[ACTIVE] ExecuteThread: '4' for queue: 'weblogic.kernel.Default (self-tuning)'] ERROR [[ACTIVE] ExecuteThread: '4' for queue: 'weblogic.kernel.Default (self-tuning)']: DONE Writing batch to DB\n\n2011-10-13/10:03:21.130/EDT [[ACTIVE] ExecuteThread: '4' for queue: 'weblogic.kernel.Default (self-tuning)'] ERROR [[ACTIVE] ExecuteThread: '4' for queue: 'weblogic.kernel.Default (self-tuning)']: java.io.FileNotFoundException: /tmp/poifiles/poi-ooxml-801119811.tmp (No such file or directory)\n\n       at java.io.FileOutputStream.open(Native Method)\n\n       at java.io.FileOutputStream.<init>(FileOutputStream.java:179)\n\n       at java.io.FileOutputStream.<init>(FileOutputStream.java:131)\n\n       at org.apache.poi.util.PackageHelper.open(PackageHelper.java:49)\n\n       at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:176)\n\n       at com.verizon.vsii.service.fileservice.FileSvchelper.processXLSXInputStream(FileSvchelper.java:1240)\n\n       at com.verizon.vsii.service.fileservice.FileSvchelper.processBlob(FileSvchelper.java:349)\n\n       at fileprocessor.FileSvc.processBlob(FileSvc.java:84)\n\n       at sun.reflect.GeneratedMethodAccessor531.invoke(Unknown Source)\n\n       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\n\n       at java.lang.reflect.Method.invoke(Method.java:597)\n\n       at weblogic.wsee.jaxws.WLSInstanceResolver$WLSInvoker.invoke(WLSInstanceResolver.java:92)\n\n       at weblogic.wsee.jaxws.WLSInstanceResolver$WLSInvoker.invoke(WLSInstanceResolver.java:74)\n\n       at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:151)\n\n       at com.sun.xml.ws.server.sei.EndpointMethodHandlerImpl.invoke(EndpointMethodHandlerImpl.java:265)\n\n       at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:100)\n\n       at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:604)\n\n       at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:563)\n\n       at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:548)\n\n       at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:445)\n\n       at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:373)\n\n       at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:524)\n\n       at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:255)\n\n       at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:140)\n\n       at weblogic.wsee.jaxws.WLSServletAdapter.handle(WLSServletAdapter.java:208)\n\n       at weblogic.wsee.jaxws.HttpServletAdapter$AuthorizedInvoke.run(HttpServletAdapter.java:310)\n\n       at weblogic.wsee.jaxws.HttpServletAdapter.post(HttpServletAdapter.java:223)\n\n       at weblogic.wsee.jaxws.JAXWSServlet.doPost(JAXWSServlet.java:124)\n\n       at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)\n\n       at weblogic.wsee.jaxws.JAXWSServlet.service(JAXWSServlet.java:79)\n\n       at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)\n\n       at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)\n\n       at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)\n\n       at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:300)\n\n       at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:26)\n\n       at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)\n\n       at oracle.dms.wls.DMSServletFilter.doFilter(DMSServletFilter.java:330)\n\n       at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)\n\n       at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.doIt(WebAppServletContext.java:3684)\n\n       at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3650)\n\n       at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)\n\n       at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:121)\n\n       at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2268)\n\n       at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174)\n\n       at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1446)\n\n       at weblogic.work.ExecuteThread.execute(ExecuteThread.java:201)\n\n       at weblogic.work.ExecuteThread.run(ExecuteThread.java:173)", "id": 150654, "time": "2011-10-17T07:39:48Z", "creator": "sundar.somasundaram@verizon.com", "creation_time": "2011-10-17T07:39:48Z", "is_private": false, "attachment_id": null}, {"count": 1, "attachment_id": null, "bug_id": 52041, "is_private": false, "id": 150656, "time": "2011-10-17T09:17:23Z", "creator": "apache@gagravarr.org", "creation_time": "2011-10-17T09:17:23Z", "tags": [], "text": "It looks like you're passing in an InputStream, and something in your weblogic environment is preventing POI turning that into a temp file\n\nYou should either pass a File directly to POI (rather than an InputStream), or fix the temp file handling in your weblogic setup"}, {"count": 2, "tags": [], "bug_id": 52041, "attachment_id": null, "text": "This happens in Linux environment(Production System). This error happens occasionally.pls provide us the solution to fix the problem.Pls provide your inputs on Code level changes, if possible.\n\nNote:\n\nWe are working with windows platform(Development Environment).", "id": 150707, "time": "2011-10-18T10:07:08Z", "creator": "sundar.somasundaram@verizon.com", "creation_time": "2011-10-18T10:07:08Z", "is_private": false}, {"count": 3, "tags": [], "bug_id": 52041, "text": "This happens in Linux environment(Production System). This error happens\noccasionally.pls provide us the solution to fix the problem.Pls provide your\ninputs on Code level changes, if possible.\n\nIs it possible to replicate the same error in our development environment?\nAnd moreover , in Production Environment this error is happenning occasionally.\nOnce we restart our application in production environment, then it is working fine.\n\nAs per your earlier reply , \n\n1)if weblogic server is prohibiting the POI API in creating the temp file, then it must prohibit everytime. But for us ,only on few occasion , we are getting this Exception. \n\n2) We can not pass File object to XSSFWorkbook API . It accepts only InputStream\n\n    Please provide us a solution solve this  Production issue.\n\nNote:\nWe are working with windows platform(Development Environment).", "id": 150708, "time": "2011-10-18T10:29:53Z", "creator": "sundar.somasundaram@verizon.com", "creation_time": "2011-10-18T10:29:53Z", "is_private": false, "attachment_id": null}, {"count": 4, "tags": [], "creator": "apache@gagravarr.org", "attachment_id": null, "text": "(In reply to comment #3)\n> 2) We can not pass File object to XSSFWorkbook API . It accepts only\n> InputStream\n\nIt accepts an OPCPackage, which can be created from a File\n\n\n>     Please provide us a solution solve this  Production issue.\n\nYou should probably talk to someone you have a support agreement with for your proprietary platform", "id": 150709, "time": "2011-10-18T10:34:57Z", "bug_id": 52041, "creation_time": "2011-10-18T10:34:57Z", "is_private": false}, {"count": 5, "tags": [], "bug_id": 52041, "attachment_id": null, "id": 150743, "time": "2011-10-19T06:14:18Z", "creator": "sundar.somasundaram@verizon.com", "creation_time": "2011-10-19T06:14:18Z", "is_private": false, "text": "Thank You Nick, we have created a OPCPackage object, passed that as an parameter to OpenorCreate method in XSSFWorkbook class, thus we have solved the issue.\n\nBut we are not able to generate the exception again, so that is not yet tested."}, {"count": 6, "tags": [], "creator": "sundar.somasundaram@verizon.com", "attachment_id": null, "text": "Hi Nick,\n       I came to know that \"because of default System temp folder's(C:\\DOCUME~1\\v412393\\LOCALS~1\\Temp) privilages, the 2nd user is getting this exception\" so I have changed the System property for java.io.tmpdir to a comman drive space (c:\\temp). Can u pls suggest me in this.", "id": 152976, "time": "2012-01-20T16:21:14Z", "bug_id": 52041, "creation_time": "2012-01-20T16:21:14Z", "is_private": false}, {"count": 7, "tags": [], "creator": "sundar.somasundaram@verizon.com", "attachment_id": null, "text": "(In reply to comment #6)\n> Hi Nick,\n>        I came to know that \"because of default System temp\n> folder's(C:\\DOCUME~1\\v412393\\LOCALS~1\\Temp) privilages, the 2nd user is getting\n> this exception(FILE NOT FOUND) in LINUX environment, so I have changed the System property for java.io.tmpdir to a\n> comman drive space (c:\\temp). Can u pls suggest me in this.", "id": 153034, "time": "2012-01-23T07:31:14Z", "bug_id": 52041, "creation_time": "2012-01-23T07:31:14Z", "is_private": false}, {"count": 8, "tags": [], "bug_id": 52041, "text": "That's is not a POI issue, that depends entirely on your Java setup", "id": 153104, "time": "2012-01-24T14:55:29Z", "creator": "apache@gagravarr.org", "creation_time": "2012-01-24T14:55:29Z", "is_private": false, "attachment_id": null}, {"count": 9, "tags": [], "text": "(In reply to comment #8)\n> That's is not a POI issue, that depends entirely on your Java setup\n\n\nHi Nick,\n        Thanks for reply. \nCan you please suggest me what are all the configurations which I have to cross check regarding the Java setup on my LINUX enviroment? \n\nIn one of the blog I saw that POIFILES directory is created during run time under the tmp folder in LINUX.So is there anything to check on the folder path permission level settings?\n\nBut as of now we are not getting any PERMISSION DENIED error.\n\nWaiting for your reply .\n\nThanks.", "attachment_id": null, "id": 153106, "creator": "sundar.somasundaram@verizon.com", "time": "2012-01-24T15:44:49Z", "bug_id": 52041, "creation_time": "2012-01-24T15:44:49Z", "is_private": false}, {"count": 10, "tags": [], "creator": "dfisher@jmlafferty.com", "attachment_id": null, "id": 153126, "time": "2012-01-24T19:54:05Z", "bug_id": 52041, "creation_time": "2012-01-24T19:54:05Z", "is_private": false, "text": "Hi Sundar,\n\nThis is no longer a POI question. It is a Java question.\n\nTake a look at http://rationalpi.wordpress.com/2007/01/26/javaiotmpdir-inconsitency/\n\nPerhaps it will help. If not then please seek help elsewhere.\n\nRegards,\nDave"}]