[{"count": 0, "tags": [], "creator": "gorka.sanz@keensoft.es", "attachment_id": 32069, "is_private": false, "id": 178167, "time": "2014-09-29T08:41:15Z", "bug_id": 57037, "creation_time": "2014-09-29T08:41:15Z", "text": "Created attachment 32069\nsample saved with libreoffice 4.3\n\nThe following sample creates an exception wheh try to open it with POI\n\nThe sample was created with libreoffice 4.3\nIf I open and save the sample file with msoffice and libreoffice 4.2, the test works\n\n\n\nI have tried versions 3.9, 3.10-final and 3.11-beta2\n\n\norg.apache.poi.hssf.record.RecordFormatException: Leftover 486 bytes in subrecord data [15, 00, 12, 00, 19, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 99, DC, 1F, 7F, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, FF, FF, FF, FF, 00, 00, 00, 00, 00, 00, 00, 00, 02, 00, 00, 00, 03, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, FF, FF, FF, FF, 00, 00, 00, 00, 00, 00, 00, 00, FF, FF, FF, FF, FF, FF, FF, FF, 00, 00, 00, 00, FF, FF, FF, FF, E0, CF, 95, DC, 1F, 7F, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 77, EA, 07, 00, 00, 00, 04, 00, 02, 00, 00, 00, FF, FF, FF, FF, AC, A2, 85, 03, 00, 00, 00, 00, 00, 80, 01, 00, 00, 80, 00, 00, 00, 80, 01, 00, 00, 80, 13, 00, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, 01, 01, 00, 00, 00, 00, 00, 00, B8, 37, 79, EF, 1F, 7F, 00, 00, B8, 37, 79, EF, 1F, 7F, 00, 00, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF, FF]\n\tat org.apache.poi.hssf.record.ObjRecord.<init>(ObjRecord.java:110)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:526)\n\tat org.apache.poi.hssf.record.RecordFactory$ReflectionConstructorRecordCreator.create(RecordFactory.java:87)\n\tat org.apache.poi.hssf.record.RecordFactory.createSingleRecord(RecordFactory.java:338)\n\tat org.apache.poi.hssf.record.RecordFactoryInputStream.readNextRecord(RecordFactoryInputStream.java:310)\n\tat org.apache.poi.hssf.record.RecordFactoryInputStream.nextRecord(RecordFactoryInputStream.java:276)\n\tat org.apache.poi.hssf.record.RecordFactory.createRecords(RecordFactory.java:480)\n\tat org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:315)\n\tat org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:278)\n\tat org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:213)\n\tat org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:361)\n\tat org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:342)\n\tat readers.xls.GenericXLSReader.open(GenericXLSReader.java:39)"}, {"count": 1, "tags": [], "text": "It seems this file is actually corrupted, MS Excel also crashes when I try to open it, based on that this sounds more like a bug in LibreOffice...", "is_private": false, "bug_id": 57037, "id": 178636, "time": "2014-10-21T10:54:37Z", "creator": "dominik.stadler@gmx.at", "creation_time": "2014-10-21T10:54:37Z", "attachment_id": null}, {"count": 2, "tags": [], "bug_id": 57037, "attachment_id": null, "text": "For the records, Excel is not crashing always, but crashed once when I saved the file. I would expect that the file is not created 100% correctly by LibreOffice, but Excel can compensate usually, while POI actively refuses invalid content.", "id": 178637, "time": "2014-10-21T11:04:51Z", "creator": "dominik.stadler@gmx.at", "creation_time": "2014-10-21T11:04:51Z", "is_private": false}, {"count": 3, "tags": [], "creator": "sasikumar.pallekonda@qfor.com", "attachment_id": null, "id": 179214, "time": "2014-11-21T06:32:18Z", "bug_id": 57037, "creation_time": "2014-11-21T06:32:18Z", "is_private": false, "text": "We are also having the same problem and want to know how to fix the issue.\n\nWe have a excel template, and from our web application, we download the file (using POI) and enter data feed and submit for impor process.\n\nTesters have Libre Office to download the template, enter data and save it in FTP folder.  When this process is done using LibreOffice 4.3.4.1, we get the above problem, where as with LibreOffice 3.7, this doesn't exist.\n\nAlso, with MS excel also we dont see this problem"}]