[{"count": 0, "tags": [], "text": "Request.java, lines 2876-2895:\nAfter catching e.g. SizeException and setting the reason to POST_TOO_LARGE, in the following finally-block the reason is set to UNKNOWN. \nSo, the only reason that is ever set up is UNKNOWN.\n\nThe problem is with the if-statement in finally-block.", "is_private": false, "id": 199847, "creator": "bartoszarciemowicz@gmail.com", "time": "2017-07-17T10:38:53Z", "bug_id": 61311, "creation_time": "2017-07-17T10:38:53Z", "attachment_id": null}, {"count": 1, "tags": [], "bug_id": 61311, "attachment_id": null, "id": 199849, "time": "2017-07-17T11:01:47Z", "creator": "remm@apache.org", "creation_time": "2017-07-17T11:01:47Z", "is_private": false, "text": "I agree the algorithm looks weird.\nProbably something like: if (!success && !parameters.isParseFailed()) would do what's needed there, and set UNKNOWN only if no reason was set before."}, {"attachment_id": null, "tags": [], "creator": "markt@apache.org", "text": "It looks weird but it is correct. The implementation of setParseFailedReason() only updates the reason if no reason is set.\n\nA more efficient finally block is almost certainly possible but the current code is intended to be robust with respect to changes in the rest of the method.\n\nI'll add a comment for future reference.", "count": 2, "id": 199856, "time": "2017-07-17T22:40:53Z", "bug_id": 61311, "creation_time": "2017-07-17T22:40:53Z", "is_private": false}]