[{"count": 0, "tags": [], "bug_id": 6999, "text": "When requesting localhost:8080/examples/jsp/db/list.jsp and consequent\ninstantiation \nof db.ConnectionBean and during getConnection() from java.sql.DataSource \nI get the following exception:\njavax.servlet.ServletException: class db.ConnectionBean : java.sql.SQLException:\nCan't call commit when autocommit=true\n(stack trace is at the bottom of this text).\n\nDatabase is MySQL--3.23.49a\nJDBC driver is mm.mysql-2.0.8-bin.jar\nTyrex: tyrex-0.9.7.0.jar\nJDK 1.4\n\nWith the stuff above Tomcat 4.0.1 works (besides the real connection pooling is\nnot provided).\n\nWith this release of Tomcat I debugged the Tyrex code and found out that it\nattempts \nto do commit() during DataSource.getConnection().\n\nRelated piece of server.xml:\n\n         <Resource name=\"lev/DataSource\" auth=\"Container\"\n                    type=\"javax.sql.DataSource\"/>\n          <ResourceParams name=\"lev/DataSource\"> \n             <parameter><name>user</name><value>wv</value></parameter>\n            <parameter><name>password</name><value>wv</value></parameter>\n            <parameter><name>driverClassName</name>\n              <value>org.gjt.mm.mysql.Driver</value></parameter> \n            <parameter><name>driverName</name>\n              <value>jdbc:mysql://localhost:3306/WV</value></parameter> \n          </ResourceParams>\n\nReleated fragment of $CATALINA_HOME/webapps/examples/WEB-INF/web.xml:\n\n    <resource-ref>\n      <res-ref-name>lev/DataSource</res-ref-name>\n      <res-type>javax.sql.DataSource</res-type>\n      <res-auth>Container</res-auth>\n      <res-sharing-scope>Shareable</res-sharing-scope>\n    </resource-ref>\n\nRelated fragment of list.jsp:\n\n  <%@ include file=\"/jsp/db/defs.jsp\" %>\n  <%@ page import = \"db.ConnectionBean\" %>\n  <%@ page import = \"base.*\" %>\n  <%@ page import = \"java.lang.StrictMath\" %>\n\n\n  <jsp:useBean id=\"db\" class=\"db.ConnectionBean\" scope=\"request\"/>\n\nRelated piece of db.ConnectionBean:\n\n   public class ConnectionBean extends base.BaseBean{\n\n      ...\n      public ConnectionBean() throws NamingException, MyException, SQLException\n{\n\t_baseIt++;        \n\tsuper.BaseBean();\n\n\tsuper.openConnection();  // EXCEPTION IS THROWN FROM HERE\n\tcreateTables();\n      }\n      ...\n    }\n\nRelated piece of base.BaseBean:\n\n--------------- cut here --------------------------\npackage base;\n\n\nimport javax.servlet.http.*;\nimport java.util.*;\nimport java.io.*;\nimport javax.naming.NamingException;\nimport javax.naming.Context;\nimport javax.naming.InitialContext;\nimport javax.naming.NamingEnumeration;\nimport javax.naming.Binding;\nimport javax.naming.directory.InitialDirContext;\nimport java.sql.*;\nimport javax.sql.*;\nimport base.DBTable;\nimport javazoom.upload.*;\n\n\nimport base.MyException;\n\npublic class BaseBean\n{\n    private Hashtable _tables;\n    private DataSource _ds = null;\n    private String _dbkind = null;\n    protected Connection _con = null;\n\n    public void BaseBean() throws NamingException, MyException, SQLException\n    {\t\n\n\t_tables = new Hashtable();\n\n        Context ctx  = new InitialContext();\n\tif (_ds == null)\n          {\n              envCtx = (Context)ctx.lookup(\"java:comp/env\");\n              _ds = (DataSource)envCtx.lookup(\"lev/DataSource\");\n\t      if (_ds == null)\n\t\tthrow new MyException(\"Bad data source\");\n\n\t  }\n\n    }\n\n    protected void finalize() throws SQLException\n    { \n\tjava.util.Date d = new java.util.Date(System.currentTimeMillis());\n\tSystem.err.println(\"finalize at \" + d);\n\tif (_con != null) _con.close(); \n    }\n\n    public void  openConnection() throws SQLException, MyException \n    {\n\tif (_con == null)\n\t    {\n\t\tif (_ds == null)\n\t\t    throw new MyException(\"Bad datasource\");\n\t\t_con = _ds.getConnection();  // EXCEPTION IS THROWN FROM HERE !!!\n\t\tif (_con == null)  \n\t\t    throw new MyException(\"Bad connection\");\n\t\t_dbkind = _con.getMetaData().getDatabaseProductName();\n\t    }\n\t\n    }\n\n  // ...\n\n}\n------------------ cut here ---------------------------\n\nI tried mm.mysql-2.0.11-bin.jar but with the same result.\n\nStack trace:\n------------------------- cut here ---------------------------------------\nApache Tomcat/4.0.4-b1 - HTTP Status 500 - Internal Server Error\n\n\n\ntype Exception report\n\nmessage Internal Server Error\n\ndescription The server encountered an internal error (Internal Server Error)\nthat prevented it from fulfilling this request.\n\nexception \n\njavax.servlet.ServletException: class db.ConnectionBean : java.sql.SQLException:\nCan't call commit when autocommit=true\n        at\norg.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:463)\n        at org.apache.jsp.list$jsp._jspService(list$jsp.java:608)\n        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)\n        at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)\n        at\norg.apache.jasper.servlet.JspServlet$JspServletWrapper.service(JspServlet.java:202)\n        at\norg.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:382)\n        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:474)\n        at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)\n        at\norg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:247)\n        at\norg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:193)\n        at\norg.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:243)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:566)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:472)\n        at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:943)\n        at\norg.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:190)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:566)\n        at\norg.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:564)\n        at\norg.apache.catalina.valves.CertificatesValve.invoke(CertificatesValve.java:246)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:564)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:472)\n        at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:943)\n        at\norg.apache.catalina.core.StandardContext.invoke(StandardContext.java:2347)\n        at\norg.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:180)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:566)\n        at\norg.apache.catalina.valves.ErrorDispatcherValve.invoke(ErrorDispatcherValve.java:170)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:564)\n        at\norg.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:170)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:564)\n        at\norg.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:468)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:564)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:472)\n        at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:943)\n        at\norg.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:174)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:566)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:472)\n        at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:943)\n        at\norg.apache.catalina.connector.http.HttpProcessor.process(HttpProcessor.java:1017)\n        at\norg.apache.catalina.connector.http.HttpProcessor.run(HttpProcessor.java:1115)\n        at java.lang.Thread.run(Thread.java:539)\n\nroot cause \n\njava.lang.InstantiationException: class db.ConnectionBean :\njava.sql.SQLException: Can't call commit when autocommit=true\n        at org.apache.jsp.list$jsp._jspService(list$jsp.java:97)\n        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)\n        at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)\n        at\norg.apache.jasper.servlet.JspServlet$JspServletWrapper.service(JspServlet.java:202)\n        at\norg.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:382)\n        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:474)\n        at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)\n        at\norg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:247)\n        at\norg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:193)\n        at\norg.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:243)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:566)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:472)\n        at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:943)\n        at\norg.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:190)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:566)\n        at\norg.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:564)\n        at\norg.apache.catalina.valves.CertificatesValve.invoke(CertificatesValve.java:246)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:564)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:472)\n        at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:943)\n        at\norg.apache.catalina.core.StandardContext.invoke(StandardContext.java:2347)\n        at\norg.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:180)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:566)\n        at\norg.apache.catalina.valves.ErrorDispatcherValve.invoke(ErrorDispatcherValve.java:170)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:564)\n        at\norg.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:170)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:564)\n        at\norg.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:468)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:564)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:472)\n        at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:943)\n        at\norg.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:174)\n        at\norg.apache.catalina.core.StandardPipeline.invokeNext(StandardPipeline.java:566)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:472)\n        at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:943)\n        at\norg.apache.catalina.connector.http.HttpProcessor.process(HttpProcessor.java:1017)\n        at\norg.apache.catalina.connector.http.HttpProcessor.run(HttpProcessor.java:1115)\n        at java.lang.Thread.run(Thread.java:539)", "id": 11611, "time": "2002-03-09T17:18:05Z", "creator": "lev@peterlink.ru", "creation_time": "2002-03-09T17:18:05Z", "is_private": false, "attachment_id": null}, {"text": "*** Bug 7693 has been marked as a duplicate of this bug. ***", "tags": [], "bug_id": 6999, "attachment_id": null, "count": 1, "id": 12829, "time": "2002-04-04T21:46:51Z", "creator": "remm@apache.org", "creation_time": "2002-04-04T21:46:51Z", "is_private": false}, {"count": 2, "attachment_id": null, "creator": "remm@apache.org", "text": "The change which caused this has been reverted (now using again the Tyrex\nDataSource which doesn't do much).\n4.1.3 Beta uses commons-dbcp as the DataSource provider, which will hopefully\nprove to be easier to use (although it is more limited feature-wise).", "id": 17260, "time": "2002-06-06T01:17:22Z", "bug_id": 6999, "creation_time": "2002-06-06T01:17:22Z", "tags": [], "is_private": false}]